version: '3.1'

services:
  zoo1:
    image: zookeeper:3.6.1
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    expose:
      - 2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOO_CFG_EXTRA: "extendedTypesEnabled=true emulate353TTLNodes=true"

  zoo2:
    image: zookeeper:3.6.1
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
    expose:
      - 2182
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOO_CFG_EXTRA: "extendedTypesEnabled=true emulate353TTLNodes=true"

  zoo3:
    image: zookeeper:3.6.1
    restart: always
    hostname: zoo3
    ports:
      - 2183:2181
    expose:
      - 2183
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
      ZOO_CFG_EXTRA: "extendedTypesEnabled=true emulate353TTLNodes=true"

  kafka1:
    image: kafka:0.3
    restart: always
    hostname: kafka1
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    ports:
      - 9092:9092
    expose:
      - 9093
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2182,zoo3:2183
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka1:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

  monitor1:
    image: kafka-monitor:0.3
    restart: always
    hostname: monitor1
    command: java -cp "WatcherKafka.jar:../jars/*" main.WatcherKafka
    depends_on:
      - kafka1
