version: '3.1'

services:
  zoo1:
    image: zookeeper:3.6.1
    restart: always
    hostname: zoo1
    networks:
      kafka-net:
        ipv4_address: 172.21.0.2
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=172.21.0.3:2888:3888;2181 server.3=172.21.0.4:2888:3888;2181 server.4=172.21.0.10:2888:3888;2181
      ZOO_CFG_EXTRA: "extendedTypesEnabled=true emulate353TTLNodes=true"

  zoo2:
    image: zookeeper:3.6.1
    restart: always
    hostname: zoo2
    networks:
      kafka-net:
        ipv4_address: 172.21.0.3
    depends_on:
      - zoo1
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=172.21.0.2:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=172.21.0.4:2888:3888;2181 server.4=172.21.0.10:2888:3888;2181
      ZOO_CFG_EXTRA: "extendedTypesEnabled=true emulate353TTLNodes=true"

  zoo3:
    image: zookeeper:3.6.1
    restart: always
    hostname: zoo3
    networks:
      kafka-net:
        ipv4_address: 172.21.0.4
    depends_on:
      - zoo1
      - zoo2
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=172.21.0.2:2888:3888;2181 server.2=172.21.0.3:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181 server.4=172.21.0.10:2888:3888;2181
      ZOO_CFG_EXTRA: "extendedTypesEnabled=true emulate353TTLNodes=true"

  zoo4:
    image: zookeeper:3.6.1
    restart: always
    hostname: zoo4
    networks:
      kafka-net:
        ipv4_address: 172.21.0.10
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    ports:
      - 2184:2181
    environment:
      ZOO_MY_ID: 4
      ZOO_SERVERS: server.1=172.21.0.2:2888:3888;2181 server.2=172.21.0.3:2888:3888;2181 server.3=172.21.0.4:2888:3888;2181 server.4=0.0.0.0:2888:3888;2181
      ZOO_CFG_EXTRA: "extendedTypesEnabled=true emulate353TTLNodes=true"

  kafka1:
    image: icunhacorrea/kafka:latest
    restart: always
    hostname: kafka1
    networks:
      kafka-net:
        ipv4_address: 172.21.0.5
    depends_on:
      - zoo1
      - zoo2
      - zoo3
      - zoo4
    ports:
      - 9093:9092
    environment:
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_ZOOKEEPER_CONNECT: 172.21.0.2:2181,172.21.0.3:2181,172.21.0.4:2181
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: INSIDE://172.21.0.5:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

  kafka2:
    image: icunhacorrea/kafka:latest
    restart: always
    hostname: kafka2
    networks:
      kafka-net:
        ipv4_address: 172.21.0.6
    depends_on:
      - zoo1
      - zoo2
      - zoo3
      - zoo4
      - kafka1
    ports:
      - 9094:9092
    environment:
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_ZOOKEEPER_CONNECT: 172.21.0.2:2181,172.21.0.3:2181,172.21.0.4:2181
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_LISTENERS: INSIDE://172.21.0.6:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

  kafka3:
    image: icunhacorrea/kafka:latest
    restart: always
    hostname: kafka3
    networks:
      kafka-net:
        ipv4_address: 172.21.0.7
    depends_on:
      - zoo1
      - zoo2
      - zoo3
      - zoo4
      - kafka1
      - kafka2
    ports:
      - 9095:9092
    environment:
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_ZOOKEEPER_CONNECT: 172.21.0.2:2181,172.21.0.3:2181,172.21.0.4:2181
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_LISTENERS: INSIDE://172.21.0.7:9092,OUTSIDE://localhost:9095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9095
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

  monitor1:
    image: icunhacorrea/kafka-monitor:latest
    restart: always
    hostname: monitor1
    networks:
      kafka-net:
        ipv4_address: 172.21.0.8
    command: java -cp "WatcherKafka.jar:../jars/*" main.WatcherKafka
    depends_on:
      - zoo1
      - zoo2
      - zoo3
      - zoo4
      - kafka1
      - kafka2
      - kafka3
    ports:
      - 6666:6666

  producer:
    image: icunhacorrea/kafka-producer:latest
    restart: always
    networks:
      kafka-net:
        ipv4_address: 172.21.0.9
    sysctls:
        net.ipv4.tcp_retries1: 2
        net.ipv4.tcp_retries2: 4
        #net.ipv4.tcp_syn_retries: 1
        #net.ipv4.tcp_synack_retries: 0
        #net.ipv4.tcp_dsack: 0
        #net.ipv4.tcp_sack: 0
        #net.ipv4.tcp_keepalive_time: 0
    hostname: producer
    networks:
      kafka-net:
        ipv4_address: 172.21.0.9
    command: tail -f /dev/null
    depends_on:
      - zoo1
      - zoo2
      - zoo3
      - zoo4
      - kafka1
      - kafka2
      - kafka3
      - monitor1

networks:
  kafka-net:
    driver: macvlan
    driver_opts:                         
      com.docker.network.driver.mtu: 1500
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24
